exp/urls.py
from django.urls import path

from exp import views
from exp.apps import ExpConfig

app_name = ExpConfig.name

urlpatterns = [
    path('', views.MainPageView.as_view(), name='index'),
    path('about', views.AboutUsView.as_view(), name='about'),
    path('employees', views.OurEmployeesView.as_view(), name='employ'),
    path("news/", views.NewsListView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path(
        "news/<int:pk>/detail",
        views.NewsDetailView.as_view(),
        name="news_detail",
    ),
    path(
        "news/<int:pk>/update",
        views.NewsUpdateView.as_view(),
        name="news_update",
    ),
    path(
        "news/<int:pk>/delete",
        views.NewsDeleteView.as_view(),
        name="news_delete",
    ),
]

expert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exp.urls', namespace="exp")),
    path("authapp/", include("authapp.urls", namespace="authapp"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = "News"
        verbose_name_plural = "News"
        ordering = ("-created",)

exp/views.py
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView, View
from exp import models as exp_models


class MainPageView(TemplateView):
    template_name = "exp/base.html"


class AboutUsView(TemplateView):
    template_name = "exp/aboutUs.html"


class OurEmployeesView(TemplateView):
    template_name = "exp/ourEmployees.html"


class NewsListView(ListView):
    model = exp_models.News
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = exp_models.News
    fields = "__all__"
    success_url = reverse_lazy("exp:news")
    permission_required = ("exp.add_news",)


class NewsDetailView(DetailView):
    model = exp_models.News


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = exp_models.News
    fields = "__all__"
    success_url = reverse_lazy("exp:news")
    permission_required = ("exp.change_news",)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = exp_models.News
    success_url = reverse_lazy("exp:news")
    permission_required = ("exp.delete_news",)

exp/templates/exp/aboutUs.html
{% extends 'exp/base.html' %}

{% block content %}
    <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
        <div class="card h-100 shadow">
            <div class="card-body">
                <div style="position:relative;overflow:hidden;"><a
                        href="https://yandex.ru/maps/2/saint-petersburg/?utm_medium=mapframe&utm_source=maps"
                        style="color:#eee;font-size:12px;position:absolute;top:0px;">Петропавловская
                    крепость</a><a
                        href="https://yandex.ru/maps/2/saint-petersburg/house/blagodatnaya_ulitsa_69k1d/Z0kYdQNlTEYOQFtjfXR2d3prZA==/?ll=30.345539%2C59.876680&utm_medium=mapframe&utm_source=maps&z=17.09"
                        style="color:#eee;font-size:12px;position:absolute;top:14px;"></a><a
                        href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
                        style="color:#eee;font-size:12px;position:absolute;top:28px;"></a>
                    <iframe
                            src="https://yandex.ru/map-widget/v1/?ll=30.345539%2C59.876680&mode=search&ol=geo&ouri=ymapsbm1%3A%2F%2Fgeo%3Fdata%3DCgoxNjE3MDgxODk5ElfQoNC-0YHRgdC40Y8sINCh0LDQvdC60YIt0J_QtdGC0LXRgNCx0YPRgNCzLCDQkdC70LDQs9C-0LTQsNGC0L3QsNGPINGD0LvQuNGG0LAsIDY50Lox0JQiCg2ow_JBFbiBb0I%2C&z=17.09"
                            width="100%"
                            height="300" frameborder="0" allowfullscreen="true"
                            style="position:relative; border-radius: 4px;"></iframe>
                </div>
                <h5 class="card-title">Санкт‑Петербург</h5>
                <p class="card-text">
                <ul class="list-unstyled">
                    <li>Телефон</li>
                    <li><strong>+7-999-234-64-79</strong></li>
                </ul>
                <ul class="list-unstyled">
                    <li>Email</li>
                    <li><strong>k2foxspb@mail.ru</strong></li>
                </ul>
                <ul class="list-unstyled">
                    <li>Адрес</li>
                    <li><strong>Адрес: 196105, Санкт-Петербург,
                        ул. Благодатная, д. 69, корп. 1,
                        лит. Д, офис 3303</strong>
                    </li>
                </ul>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

exp/templates/exp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Welcome to Expert!
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://vk.com/js/api/openapi.js?169" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block messages %}
    {% include 'includes/messages.html' %}
{% endblock messages %}
{% include 'includes/navbar.html' %}

<div class="container-md">
    {% block content %}
        <div class="container">
            <h5 class="text-center">
                <p class="display-5">ЭКСПЕРТИЗЫ И ПРАВОВОЕ СОПРОВОЖДЕНИЕ
                </p>
            </h5>
        </div>
        <div class="container">
            <div id="carouselExampleFade" class=" carousel slide carousel-fade">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img height="50%" src="{% static 'img/2.jpg' %}" class="d-block w-100" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/3.jpg' %}" class="d-block w-100" alt="">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/4.jpg' %}" class="d-block w-100" alt="">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    {% endblock %}
</div>
<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>телефон</strong>
            </p>
            <div class=phone><a href="tel:+79093694701">+7 909) 369-47-01</a></div>
            <div class=phone><a href="tel:+79317068600">+7 (931) 706-86-00</a></div>

        </div>
        {# VK Widget #}
        <div id="vk_community_messages"></div>
        <script type="text/javascript">
            VK.Widgets.CommunityMessages("vk_community_messages", 177055903, {
                expanded: "0",
                tooltipButtonText: "Есть вопрос?"
            });
        </script>

    </div>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block js %}
    <script>
        $(document).ready(function () {

            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}

        });
    </script>
{% endblock js %}
</body>
</html>

exp/templates/exp/news_confirm_delete.html
{% extends 'exp/base.html' %}

{% block content %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-8 col-lg-6">
            <h2>Пометить новость удалённой?</h2>
            <p>
                Поставить отметку удаления для новости:<br>
                "{{ object.title }}" от {{ object.created }}
            </p>
            <p>
            <div class="row">
                <div class="col-6">
                    <form action="{% url 'exp:news_delete' pk=object.pk %}"
                          method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-block"
                                type="submit">Подтвердить
                        </button>
                    </form>
                </div>
                <div class="col-6">
                    <a class="btn btn-primary btn-block" href="{% url 'exp:news' %}"
                       role="button">Отмена</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

exp/templates/exp/news_detail.html
{% extends 'exp/base.html' %}

{% block title %}
{{ object.title|default:"Новости" }}
{% endblock title %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-12 col-lg-8">
    <div class="card shadow">
      <div class="card-body">
        <h5 class="card-title">{{ object.title }}</h5>
        <p class="card-text">
          {{ object.body }}
        </p>
        <a href="{% url 'exp:news' %}" class="btn btn-primary">Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

exp/templates/exp/news_form.html
{% extends 'exp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-12 col-lg-8">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit"
        class="btn btn-primary btn-block">Опубликовать</button>
    </form>
  </div>
</div>
{% endblock content %}

exp/templates/exp/news_list.html
{% extends 'exp/base.html' %}

{% block title %}
    Новости
{% endblock title %}

{% block content %}

    {% if page_num %}
        <div class="card my-2">
            <div class="card-body">
                <p class="card-text">Текущая страница: {{ page_num }}</p>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-lg-8">

            {% for item in object_list %}
                <div class="card my-2">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            {{ item.created|date:"d-m-y h-i-s" }}
                        </h6>
                        <p class="card-text">{{ item.preambule }}</p>
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'exp:news_detail' pk=item.pk %}"
                                   class="card-link">Подробнее</a>
                            </div>
                            {% if perms.exp.change_news %}
                                <div class="col-1 text-center">
                                    <a href="{% url 'exp:news_update' pk=item.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>
                                </div>
                            {% endif %}
                            {% if perms.exp.delete_news %}
                                <div class="col-1 text-center">
                                    <a href="{% url 'exp:news_delete' pk=item.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

        <div class="col-lg-4">
            <div class="card my-2 sticky-top">
                <div class="card-header">
                    Фильтры
                </div>
                <div class="card-body">
                    <form action="">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Дата от...</span>
                            </div>
                            <input type="date" class="form-control" name="dateFrom">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Дата до...</span>
                            </div>
                            <input type="date" class="form-control" name="dateTo">
                        </div>

                        <button type="submit"
                                class="btn btn-primary btn-block">Фильтровать
                        </button>
                    </form>
                </div>
            </div>

            {% if perms.exp.add_news %}
                <a class="btn btn-primary btn-block" role="button"
                   href="{% url 'exp:news_create' %}">Добавить новость</a>
            {% endif %}

        </div>

    </div>

    <div class="row justify-content-center align-items-center mt-3 mb-n3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                {# <li class="page-item"><a class="page-link" href="#">3</a></li> #}
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>
    </div>

{% endblock content %}

exp/templates/exp/ourEmployees.html
{% extends 'exp/base.html' %}
{% load static %}

{% block content %}
    <div class="container text-left">
        <div class="row">
            <div class="col-4">
                <img width="150" height="150" src="{% static 'img/Volodya.jpg' %}" class="img-thumbnail"
                     alt="">
            </div>
            <div class="col-8 card-text">
                <p>
                    &#128269;<b>Кочемировский Владимир Алексеевич</b><br>
                    &#8226; Эксперт-химик, эколог, стаж профессиональной деятельности – 40 лет, в том числе опыт
                    экспертной деятельности более 25 лет.<br>
                    &#8226; Образование: Ленинградский Государственный Университет, химический факультет (1976 – 1982
                    гг).<br>
                    &#8226; Кандидат химических наук (1989 г.),<br>
                    &#8226; Автор более 70 научных работ, индекс Хирша 15.<br>
                    &#8226; Член Палаты судебных экспертов им. Ю. Г. Корухова с 2011 г.<br>
                    &#8226; Доцент Санкт-Петербургского политехнического университета им. Петра Великого.<br>
                </p>
            </div>
        </div>
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col-4">
                    <img width="150" height="150" src="{% static 'img/я.jpg' %}" class="img-thumbnail"
                         alt="">
                </div>
                <div class="col-8 card-text">
                    <p>
                        &#10031;<b>Фокин Валерий Валерьевич</b><br>
                        &#8226; Брат жены эксперта<br>


                    </p>
                </div>

            </div>
        {% endif %}
    </div>
{% endblock %}