authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path(
        "profile_edit/<int:pk>/",
        views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
]

exp/urls.py
from django.urls import path

from exp import views
from exp.apps import ExpConfig

app_name = ExpConfig.name

urlpatterns = [
    path('', views.MainPageView.as_view(), name='index'),
    path('about', views.AboutUsView.as_view(), name='about'),
    path('employees', views.OurEmployeesView.as_view(), name='employ'),
    path("news/", views.NewsListView.as_view(), name="news"),
    path("news/create/", views.NewsCreateView.as_view(), name="news_create"),
    path(
        "news/<int:pk>/detail",
        views.NewsDetailView.as_view(),
        name="news_detail",
    ),
    path(
        "news/<int:pk>/update",
        views.NewsUpdateView.as_view(),
        name="news_update",
    ),
    path(
        "news/<int:pk>/delete",
        views.NewsDeleteView.as_view(),
        name="news_delete",
    ),
]

expert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exp.urls', namespace="exp")),
    path("authapp/", include("authapp.urls", namespace="authapp"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

exp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        verbose_name = "News"
        verbose_name_plural = "News"
        ordering = ("-created",)

exp/views.py
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView, View
from exp import models as exp_models


class MainPageView(TemplateView):
    template_name = "exp/base.html"


class AboutUsView(TemplateView):
    template_name = "exp/aboutUs.html"


class OurEmployeesView(TemplateView):
    template_name = "exp/ourEmployees.html"


class NewsListView(ListView):
    model = exp_models.News
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = exp_models.News
    fields = "__all__"
    success_url = reverse_lazy("exp:news")
    permission_required = ("exp.add_news",)


class NewsDetailView(DetailView):
    model = exp_models.News


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = exp_models.News
    fields = "__all__"
    success_url = reverse_lazy("exp:news")
    permission_required = ("exp.change_news",)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = exp_models.News
    success_url = reverse_lazy("exp:news")
    permission_required = ("exp.delete_news",)

exp/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar" href="{% url 'exp:index' %}">
            <img src="{% static 'img/111.png' %}" alt="home" style="width: 50%">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'exp:about' %}">How to find us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'exp:employ' %}">Our employees</a>
                <li class="nav-item">
                    <a class="nav-link" href="'{% url 'exp:news' %}'">News</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Profile
                    </a>
                    <ul class="dropdown-menu">

                    <li><a class="dropdown-item"
                           href="{% url 'authapp:profile_edit' pk=request.user.pk %}">edit</a></li>
                    {% if user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">admin</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'authapp:logout' %}">Exit</a></li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'authapp:login' %}">Login</a></li>
                {% endif %}


                </ul>
                </li>

            </ul>

        </div>
    </div>
</nav>